# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target "MDC-Tutorial" do
  #use_frameworks!

  pod "MaterialComponents/AppBar"
  pod "MaterialComponents/Buttons"
  pod "MaterialComponents/Collections"

end
